[package]
name = "sonotext"
version = "0.0.0"
description = "Sonotext desktop shell"
authors = ["cep5603"]
edition = "2021"

[lib]
name = "sonotext_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
